### ISSUE TITLE
Yarn migrate fails

### ISSUE THREAD

**Issue by nishontan** [leapfrogtechnology/chill#137]
## Description 
I followed steps till `To run locally, run this command from monitor, api and dashboard directories.`
when I run `yarn migrate` It crashes with the following error `The "path" argument must be one of type string, Buffer, or URL. Received type undefined`

#### Stacktrace
```
n@xps:~/Projects/tmp/chill/monitor$ yarn migrate
yarn run v1.22.4
$ knex migrate:latest
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Loading config file: undefined
internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.openSync (fs.js:435:3)
    at Object.readFileSync (fs.js:343:35)
    at Function.Utils.getStringFromFile (/home/niyo/Projects/tmp/chill/monitor/node_modules/yamljs/lib/Utils.js:284:19)
    at Function.Yaml.parseFile (/home/niyo/Projects/tmp/chill/monitor/node_modules/yamljs/lib/Yaml.js:46:21)
    at Function.Yaml.load (/home/niyo/Projects/tmp/chill/monitor/node_modules/yamljs/lib/Yaml.js:89:17)
    at Object.load [as resolve] (/home/niyo/Projects/tmp/chill/monitor/src/config/config.js:17:29)
    at Object.<anonymous> (/home/niyo/Projects/tmp/chill/monitor/knexfile.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at initKnex (/home/niyo/Projects/tmp/chill/monitor/node_modules/knex/bin/cli.js:39:9)
    at Command.commander.command.description.option.action (/home/niyo/Projects/tmp/chill/monitor/node_modules/knex/bin/cli.js:178:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nishontan** [comment]
Doing 
`export CHILL_CONFIG=../chill.yml`
fixed the issue
